### ISSUE TITLE
enable_weeks for normal_shop_item inconsistent

### ISSUE THREAD

**Issue by Chakratos** [Invasor-de-Fronteiras/Erupe#25]
It takes the week of the year and mod's it by 4 but there are month with 5 or even 6 weeks and even in January 2022 the feature would be out of sync, since the 5. and 6. week would be seen as 1. and 2. week of February.

Just take the current week for example: Its week 31 of the year, 31 % 4 = 3 but currently we have the first week of August

Did i overlooked something or maybe not understand the feature correctly?

Thanks for your work!

**Comment by Tsugami** [comment]
Hi Chakratos!

First, I want to tell you to feel free to call us on Discord too, we are totally accessible on Discord :))

Your math is right but the goal was not weeks in the exact month, it was just rotating between **4** `road shop`, I could put up to 10 `road shop`. @rainapepe did this part, I'm waiting for him to answer you with more property

**Comment by rainapepe** [comment]
Hi Chakratos! =D

It's just like Tsugami said, the goal was to create 4 "roadshop" to rotate weekly just to be able to place unique items in each of the 4 weeks regardless of the week in the month, we could increase it to 10 roadshop to rotate 10 different transmog for example.

The problem with making the exact week of the month is that there will be weeks with few days

**Comment by Chakratos** [comment]
Hey, thanks for the answers!
It seems that i just did not get what the feature actually does ^^

**Comment by Tsugami** [comment]
@Chakratos  I'm closing this issue, if you want to ask more questions, you can create new issues in [Kelbi](https://github.com/Invasor-de-Fronteiras/Kelbi) or call us on [Discord]( https://discord.gg/Agjkad7zdU). 👋 


Also, very cool you came to talk to us, you are the first person other than Malckyour on CE. 😊
